#---------------------------多環境配置-----------------------------
spring:
  config:
    activate:
      on-profile: local
  # postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=test
    username: root
    password: 123456
    spring.datasource.driver-class-name: org.postgresql.Driver
  # Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true