#---------------------------多環境配置-----------------------------
spring:
  config:
    activate:
      on-profile: local
  #elasticsearch
  elasticsearch:
    uris: 127.0.0.1:9200
    username: elastic
    password: 123456
  # postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=demo
    username: root
    password: 123456
    spring.datasource.driver-class-name: org.postgresql.Driver
  # Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
    # elasticsearch
    elasticsearch:
      repositories:
        enabled: true


# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true