server:
  servlet:
    context-path: /auth
  port: 2424
spring:
  application:
    name: auth-service
# admin
  boot:
    admin:
      client:
        url: http://localhost:2000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true